CREATE DATABASE IF NOT EXISTS  ECOMMERCE;

USE ECOMMERCE;

CREATE TABLE UTENTE(
    USERNAME VARCHAR(50),
    NOME VARCHAR (50),
    COGNOME VARCHAR (50),
    EMAIL VARCHAR (50),
    PRIMARY KEY (USERNAME)
);
CREATE TABLE ORDINE(
    CODICE INT,
    DATA_ORDINE DATE,
    STATO VARCHAR (200),
    USERNAME_UTENTE VARCHAR(50),
    PRIMARY KEY (CODICE),
    FOREIGN KEY (USERNAME_UTENTE) REFERENCES UTENTE(USERNAME)
);
CREATE TABLE PRODOTTO(
    NOME VARCHAR(50),
    PREZZO DECIMAL(6,2),
    QUANTITA INT,
    PRIMARY KEY (NOME)
);
CREATE TABLE CATEGORIA_PROD(
    NOME VARCHAR(50),
    CATEGORIA VARCHAR(50),
    FOREIGN KEY (NOME) REFERENCES PRODOTTO(NOME)
);
CREATE TABLE COMPOSTO(
    NOME VARCHAR(50),
    CODICE INT,
    QUANTITA INT,
    FOREIGN KEY (NOME) REFERENCES PRODOTTO(NOME),
    FOREIGN KEY (CODICE) REFERENCES ORDINE(CODICE)
);
CREATE TABLE SPEDIZIONE(
    CODICE INT,
    DATA_DI_SPED DATE,
    INDIRIZZO VARCHAR (200),
    FOREIGN KEY(CODICE) REFERENCES ORDINE(CODICE)
);