USE ECOMMERCE;
-- QUERY 1
/* 
UPDATE PRODOTTO
SET PREZZO=PREZZO*1.1
WHERE PREZZO>100.00;

UPDATE PRODOTTO
SET PREZZO=PREZZO*1.15
WHERE PREZZO<=100;
*/
-- QUERY 2
/* 
ALTER TABLE ORDINE
DROP COLUMN STATO;
*/
-- QUERY 3
/*
UPDATE PRODOTTO
SET QUANTITA=QUANTITA +1;
*/
-- QUERY 4
/*
INSERT INTO CATEGORIA_PROD
VALUES ('Smartwatch','Abbigliamento');
*/
-- QUERY 5
SELECT O.*,U.*,S.*
FROM ORDINE O
JOIN UTENTE U ON O.USERNAME_UTENTE = U.USERNAME
JOIN SPEDIZIONE S ON O.CODICE = S.CODICE;
-- QUERY 6
SELECT CATEGORIA, COUNT(NOME) AS NUM_PRODOTTI
FROM CATEGORIA_PROD
GROUP BY CATEGORIA
ORDER BY CATEGORIA ASC;
-- QUERY 7
SELECT U.USERNAME, IFNULL(COUNT(O.CODICE), 0) AS NUM_ORDINI
FROM UTENTE U
LEFT JOIN ORDINE O ON U.USERNAME = O.USERNAME_UTENTE
GROUP BY U.USERNAME
ORDER BY NUM_ORDINI DESC;
-- QUERY 8
SELECT AVG(PREZZO) AS PREZZO_MEDIO
FROM PRODOTTO;
-- QUERY 9
SELECT C.CODICE,
       SUM(P.PREZZO * C.QUANTITA) / COUNT(*) AS SPESA_MEDIA
FROM COMPOSTO C
JOIN PRODOTTO P ON C.NOME = P.NOME
GROUP BY C.CODICE;
-- QUERY 10
SELECT CODICE, COUNT(*) AS NUM_ARTICOLI
FROM COMPOSTO
GROUP BY CODICE;
-- QUERY 11
SELECT AVG(NUM_ARTICOLI) AS NUM_MEDIO_ARTICOLI
FROM (
    SELECT CODICE, COUNT(*) AS NUM_ARTICOLI
    FROM COMPOSTO
    GROUP BY CODICE
) AS NUM_ARTICOLI_PER_ORDINE;
-- QUERY 12
SELECT NOME, COUNT(*) AS NUM_ORDINI
FROM COMPOSTO
GROUP BY NOME
ORDER BY NUM_ORDINI DESC;
-- QUERY 13
SELECT NOME, COUNT(*) AS NUM_VENDITE
FROM COMPOSTO
GROUP BY NOME
ORDER BY NUM_VENDITE DESC
LIMIT 1;
