CREATE SCHEMA IF NOT EXISTS Azienda;

USE Azienda;

CREATE TABLE IMPIEGATO (
	NOME_BATT VARCHAR(15) NOT NULL,
    INIZ_INT CHAR,
    COGNOME VARCHAR(15) NOT NULL,
    SSN CHAR(16) NOT NULL,
    DATA_N DATE,
    INDIRIZZO VARCHAR(30),
    SESSO CHAR,
    STIPENDIO DECIMAL(10.2),
    SUPER_SSN CHAR(16),
    N_D INT NOT NULL,
    
    PRIMARY KEY (SSN),
    FOREIGN KEY (SUPER_SSN) REFERENCES IMPIEGATO (SSN)
);

CREATE TABLE DIPARTIMENTO (
	NOME_D VARCHAR(30) NOT NULL,
    NUMERO_D INT NOT NULL,
    DATA_INIZIO_D DATE,
    SSN_DIR CHAR(16) NOT NULL,
    
    PRIMARY KEY (NUMERO_D),
    FOREIGN KEY (SSN_DIR) REFERENCES IMPIEGATO (SSN)
);

CREATE TABLE SEDI_DIP (
	SEDE VARCHAR(30),
    SEDE_D INT NOT NULL,
    
    PRIMARY KEY (SEDE),
    FOREIGN KEY (SEDE_D) REFERENCES DIPARTIMENTO (NUMERO_D)
);

CREATE TABLE PROGETTO (
	NOME_P VARCHAR(30),
    NUMERO_P INT NOT NULL,
    SEDE_P VARCHAR(30),
    NUM_D INT NOT NULL,
    
    PRIMARY KEY (NUMERO_P),
    FOREIGN KEY (NUM_D) REFERENCES DIPARTIMENTO (NUMERO_D)
);

CREATE TABLE LAVORA_SU (
    SSN_I CHAR(16) NOT NULL,
    N_P INT NOT NULL,
    ORE TIME NOT NULL,
    FOREIGN KEY (N_P)
        REFERENCES PROGETTO (NUMERO_P),
    FOREIGN KEY (SSN_I)
        REFERENCES IMPIEGATO (SSN)
);
