CREATE SCHEMA IF NOT EXISTS Azienda;

USE Azienda;

CREATE TABLE DIPARTIMENTO(
    NOME_D CHAR(50),
    NUMERO_D INT NOT NULL PRIMARY KEY,
    DATA_INIZIO_DIR DATE,
    SSN_DIR CHAR(18),
    FOREIGN KEY (SSN_DIR) REFERENCES IMPIEGATO(SSN)
);

CREATE TABLE IMPIEGATO(
    NOME_BATT CHAR(30),
    INIZ_INT CHAR,
    COGNOME CHAR(30),
    SSN CHAR(18) NOT NULL PRIMARY KEY,
    DATA_N DATE,
    INDIRIZZO CHAR(200),
    SESSO CHAR,
    STIPENDIO FLOAT,
    SUPER_SSN CHAR (18),
    FOREIGN KEY (SUPER_SSN) REFERENCES IMPIEGATO(SSN)
);

CREATE TABLE SEDI_D(
    SEDE_D CHAR(50) NOT NULL PRIMARY KEY,
    NUMERO_D INT,
    FOREIGN KEY (NUMERO_D) REFERENCES DIPARTIMENTO(NUMERO_D)
);

CREATE TABLE PROGETTO(
    NOME_P CHAR(200),
    NUMERO_P INT NOT NULL PRIMARY KEY,
    SEDE_P CHAR(200),
    NUM_D INT,
    FOREIGN KEY (NUM_D) REFERENCES DIPARTIMENTO(NUMERO_D)
);

CREATE TABLE LAVORA_SU(
    SSN_I CHAR(18),
    N_P INT,
    FOREIGN KEY (SSN_I) REFERENCES IMPIEGATO(SSN),
    FOREIGN KEY (N_P)  REFERENCES PROGETTO(NUMERO_P),
    ORE INT
);